---
abstract: 'Split any SQL code into atomic statements'
author:
  - 'Emanuele Zeppieri <emazep@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-SplitStatement
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  List::MoreUtils: 0
  Moose: 0
  SQL::Tokenizer: 0
  constant: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05002
